global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'infra-monitoring-metrics'
    static_configs:
      - targets: ['infra-monitoring-system_app:8000']
    metrics_path: /metrics
    honor_labels: true
